In [34]:
# 주어진 두 행렬을 사용하여 출력 결과와 동일하게 출력하는 프로그램을 작성하시오.(단, 행렬을 추가해도됨.)

# [ np_array1]
# [[1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]]

# [ np_array2 ]
# [[5 5 5 5 5]
#  [5 5 5 5 5]
#  [5 5 5 5 5]
#  [5 5 5 5 5]
#  [5 5 5 5 5]]

# [ 출력결과1 ]
# [[6. 6. 6. 6. 6.]
#  [6. 6. 6. 6. 6.]
#  [6. 6. 6. 6. 6.]
#  [6. 6. 6. 6. 6.]
#  [6. 6. 6. 6. 6.]]

# [ 출력결과2 ]
# [[36. 6. 6. 6. 36.]
#  [6. 36. 6. 36. 6.]
#  [6. 6. 36. 6. 6.]
#  [6. 36. 6. 36. 6.]
#  [36. 6. 6. 6. 36.]]


import numpy as np

np_array1 = np.ones((5, 5))

np_array2 = np.full((5, 5), 5)

output_result1 = np_array1 + np_array2


output_result2 = np_array1 * 6
for i in range(5):
    output_result2[i, i] = 36
    output_result2[i, 4 - i] = 36


print("출력결과1")
print(output_result1)

print("\n출력결과2")
print(output_result2)



출력결과1
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]

출력결과2
[[36.  6.  6.  6. 36.]
 [ 6. 36.  6. 36.  6.]
 [ 6.  6. 36.  6.  6.]
 [ 6. 36.  6. 36.  6.]
 [36.  6.  6.  6. 36.]]


In [ ]:
출력결과1
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]

출력결과2
[[36.  6.  6.  6. 36.]
 [ 6. 36.  6. 36.  6.]
 [ 6.  6. 36.  6.  6.]
 [ 6. 36.  6. 36.  6.]
 [36.  6.  6.  6. 36.]]